variable "vpc_id" {}
variable "vpc_name" {}
variable "vpc_cidr_block" {}
variable "subnet_groups" {}
variable "nat_gateways" {}
variable "vpn_connections" {}
variable "public_igw_subnet_groups" {}
variable "nacl_connect_allowed_cidrs" {}
variable "vpc_endpoints" {}
variable "route53_resolver_settings" {}
